# Generated by Django 4.2.1 on 2023-05-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品名称')),
                ('title', models.CharField(max_length=128, verbose_name='产品中文名')),
                ('logo', models.CharField(max_length=256, null=True, verbose_name='产品logo')),
                ('cover', models.CharField(max_length=256, null=True, verbose_name='产品封面')),
                ('description', models.TextField(verbose_name='产品简介')),
                ('subDescription', models.TextField(verbose_name='产品描述')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='产品链接')),
            ],
            options={
                'verbose_name_plural': '产品信息',
            },
        ),
    ]
