# Generated by Django 4.2.1 on 2023-05-15 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='种类编号')),
                ('name', models.CharField(max_length=64, verbose_name='种类名称')),
                ('en_name', models.CharField(max_length=64, verbose_name='category')),
            ],
            options={
                'verbose_name_plural': '种类',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='城市编号')),
                ('name', models.CharField(max_length=64, verbose_name='城市名称')),
                ('en_name', models.CharField(max_length=64, verbose_name='city')),
            ],
            options={
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='RecruitType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64, verbose_name='岗位类型')),
                ('en_type', models.CharField(max_length=64, verbose_name='type')),
            ],
            options={
                'verbose_name_plural': '类型',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='岗位名称')),
                ('description', models.TextField(verbose_name='岗位描述')),
                ('requirement', models.TextField(verbose_name='岗位需求')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.category', verbose_name='种类')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.city', verbose_name='城市')),
                ('recruit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.recruittype', verbose_name='类型')),
            ],
            options={
                'verbose_name_plural': '岗位',
            },
        ),
    ]
