# Generated by Django 4.2.1 on 2023-05-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_city_recruittype_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=128, null=True, verbose_name='图片'),
        ),
    ]
