# Generated by Django 4.2.7 on 2024-05-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256, verbose_name='项目名称')),
                ('role', models.CharField(max_length=256, verbose_name='项目角色')),
                ('duration', models.CharField(max_length=256, verbose_name='持续时间')),
                ('link', models.CharField(max_length=256, null=True, verbose_name='项目链接')),
                ('description', models.TextField(verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '项目经历',
            },
        ),
        migrations.CreateModel(
            name='WorkInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('compony', models.CharField(max_length=256, verbose_name='公司名称')),
                ('position', models.CharField(max_length=256, verbose_name='职位')),
                ('duration', models.CharField(max_length=256, verbose_name='持续时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('types', models.CharField(default='正式', max_length=256, verbose_name='工作类别')),
            ],
            options={
                'verbose_name_plural': '工作经历',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('name', models.CharField(max_length=256, verbose_name='用户姓名')),
                ('phone', models.CharField(max_length=256, verbose_name='联系方式')),
                ('email', models.CharField(max_length=256, verbose_name='邮箱')),
                ('school', models.CharField(max_length=256, verbose_name='学校')),
                ('degree', models.CharField(max_length=256, verbose_name='学历')),
                ('profession', models.CharField(blank=True, max_length=256, null=True, verbose_name='专业')),
                ('duration', models.CharField(max_length=256, verbose_name='持续时间')),
                ('change_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('project_info', models.ManyToManyField(to='api.projectinfo', verbose_name='项目经历')),
                ('work_info', models.ManyToManyField(to='api.workinfo', verbose_name='工作经历')),
            ],
            options={
                'verbose_name_plural': '简历',
            },
        ),
    ]
