# Generated by Django 4.2.7 on 2024-05-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projectinfo_workinfo_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workinfo',
            old_name='compony',
            new_name='company',
        ),
    ]
