# Generated by Django 4.2.7 on 2024-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('简历筛选', '简历筛选'), ('待检阅', '待检阅'), ('面试中', '面试中'), ('待签约', '待签约'), ('已结束', '已结束')], default='简历筛选', max_length=256, verbose_name='投递状态'),
        ),
    ]
